export const cheatCodes: Array<{title: string; code: string[]}> = [
    {
        title: 'Dinheiro, saúde e armadura',
        code: [
            'R1',
            'R2',
            'L1',
            'x',
            'left',
            'down',
            'right',
            'up',
            'left',
            'down',
            'right',
            'up',
        ],
    },
    {
        title: 'Modo adrenalina',
        code: ['x', 'x', 'square', 'R2', 'L2', 'x', 'down', 'left', 'x'],
    },
    {
        title: 'Super pulo',
        code: [
            'up',
            'up',
            'triangle',
            'triangle',
            'up',
            'up',
            'left',
            'right',
            'square',
            'R2',
            'R2',
        ],
    },
    {
        title: 'Super soco',
        code: [
            'up',
            'left',
            'x',
            'triangle',
            'R1',
            'circle',
            'circle',
            'circle',
            'L2',
        ],
    },
    {
        title: 'Vida infinita',
        code: [
            'down',
            'x',
            'right',
            'left',
            'right',
            'R1',
            'right',
            'down',
            'up',
            'triangle',
        ],
    },
    {
        title: 'Capacidade pulmonar infinita',
        code: [
            'down',
            'left',
            'L1',
            'down',
            'down',
            'R2',
            'down',
            'L2',
            'down',
        ],
    },
    {
        title: 'Suicídio',
        code: [
            'right',
            'L2',
            'down',
            'R1',
            'left',
            'left',
            'R1',
            'L1',
            'L2',
            'L1',
        ],
    },
    {
        title: 'Nunca ficar faminto',
        code: [
            'square',
            'L1',
            'R2',
            'triangle',
            'up',
            'square',
            'L1',
            'up',
            'x',
        ],
    },
    {
        title: 'Mínimo de gordura e músculos',
        code: [
            'triangle',
            'up',
            'up',
            'left',
            'right',
            'square',
            'circle',
            'right',
        ],
    },
    {
        title: 'Máximo de gordura',
        code: [
            'triangle',
            'up',
            'up',
            'left',
            'right',
            'square',
            'circle',
            'down',
        ],
    },
    {
        title: 'Máximo de músculos',
        code: [
            'triangle',
            'up',
            'up',
            'left',
            'right',
            'square',
            'circle',
            'left',
        ],
    },
    {
        title: 'Máximo de respeito',
        code: [
            'L1',
            'R1',
            'triangle',
            'down',
            'R2',
            'x',
            'L1',
            'up',
            'L2',
            'L2',
            'L1',
            'L1',
        ],
    },
    {
        title: 'Máximo de sex appeal',
        code: [
            'circle',
            'triangle',
            'triangle',
            'up',
            'circle',
            'R1',
            'L2',
            'up',
            'triangle',
            'L1',
            'L1',
            'L1',
        ],
    },
    {
        title: 'Máximo de stamina',
        code: [
            'up',
            'x',
            'triangle',
            'x',
            'triangle',
            'x',
            'square',
            'R1',
            'right',
        ],
    },
    {
        title: 'Máximo de habilidades com veículos',
        code: [
            'square',
            'L2',
            'x',
            'R1',
            'L2',
            'L2',
            'left',
            'R1',
            'right',
            'L1',
            'L1',
            'L1',
        ],
    },
    {
        title: 'Habilidade com armas',
        code: [
            'down',
            'square',
            'x',
            'left',
            'R1',
            'R2',
            'left',
            'down',
            'down',
            'L1',
            'L1',
            'L1',
        ],
    },
    {
        title: 'Munição infinita',
        code: [
            'L1',
            'R1',
            'square',
            'R1',
            'left',
            'R2',
            'R1',
            'left',
            'square',
            'down',
            'L1',
            'L1',
        ],
    },
    {
        title: 'Set de armas 1',
        code: [
            'R1',
            'R2',
            'L1',
            'R2',
            'left',
            'down',
            'right',
            'up',
            'left',
            'down',
            'right',
            'up',
        ],
    },
    {
        title: 'Set de armas 2',
        code: [
            'R1',
            'R2',
            'L1',
            'R2',
            'left',
            'down',
            'right',
            'up',
            'left',
            'down',
            'down',
            'left',
        ],
    },
    {
        title: 'Set de armas 3',
        code: [
            'R1',
            'R2',
            'L1',
            'R2',
            'left',
            'down',
            'right',
            'up',
            'left',
            'down',
            'down',
            'down',
        ],
    },
    {
        title: 'Diminuir o nível de procurado',
        code: [
            'R1',
            'R1',
            'circle',
            'R2',
            'up',
            'down',
            'up',
            'down',
            'up',
            'down',
        ],
    },
    {
        title: 'Aumentar o nível de procurado',
        code: [
            'R1',
            'R1',
            'circle',
            'R2',
            'left',
            'right',
            'left',
            'right',
            'left',
            'right',
        ],
    },
    {
        title: 'Seis estrelas de nível de procurado',
        code: [
            'circle',
            'right',
            'circle',
            'right',
            'left',
            'square',
            'x',
            'down',
        ],
    },
    {
        title: 'Travar o nível de procurado',
        code: [
            'circle',
            'right',
            'circle',
            'right',
            'left',
            'square',
            'triangle',
            'up',
        ],
    },
    {
        title: 'Todos os carros têm nitro',
        code: [
            'left',
            'triangle',
            'R1',
            'L1',
            'up',
            'square',
            'triangle',
            'down',
            'circle',
            'L2',
            'L1',
            'L1',
        ],
    },
    {
        title: 'Táxis otimizados',
        code: [
            'up',
            'x',
            'triangle',
            'x',
            'triangle',
            'x',
            'square',
            'R2',
            'right',
        ],
    },
    {
        title: 'Carros voadores',
        code: [
            'square',
            'down',
            'L2',
            'up',
            'L1',
            'circle',
            'up',
            'x',
            'left',
        ],
    },
    {
        title: 'Barcos voadores',
        code: [
            'R2',
            'circle',
            'up',
            'L1',
            'right',
            'R1',
            'right',
            'up',
            'square',
            'triangle',
        ],
    },
    {
        title: 'Carros na água',
        code: ['right', 'R2', 'circle', 'R1', 'L2', 'square', 'R1', 'R2'],
    },
    {
        title: 'Carros flutuam ao serem atingidos',
        code: [
            'square',
            'R1',
            'down',
            'down',
            'left',
            'down',
            'left',
            'left',
            'L1',
            'x',
        ],
    },
    {
        title: 'Carros invisíveis',
        code: ['triangle', 'L2', 'triangle', 'R1', 'square', 'L2', 'L2'],
    },
    {
        title: 'Explodir todos os carros',
        code: [
            'R2',
            'L2',
            'R1',
            'L1',
            'L2',
            'R2',
            'square',
            'triangle',
            'circle',
            'triangle',
            'L2',
            'L1',
        ],
    },
]
